layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  linkedin: eugene-maltsev
  # medium: @your_username
  # stackoverflow: your_user_id
  telegram: @HellPirate
  # twitter: your_username
  # youtube: your_username
  # instagram: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url

topics:
  - name: React
    web_url: https://github.com/facebook/react/
    image_url: https://user-images.githubusercontent.com/6241354/55182496-df077000-519e-11e9-86ed-8fc4c5026f48.png

  - name: Programming

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
